[package]
name = "rux"
version = "0.1.0"
authors = ["mcb2003 <mikeybuchan@hotmail.co.uk>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"

[dependencies]
